<?php

namespace Coolsam\Modules\Commands;

use Coolsam\Modules\Facades\FilamentModules;
use Illuminate\Console\Command;
use Nwidart\Modules\Facades\Module;

class ModuleRouteHelperCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'module:route:helper
                            {module : The name of the module}
                            {--panel= : Specific panel ID to generate helpers for (optional)}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate route helper trait for a module';

    /**
     * Execute the console command.
     */
    public function handle(): void
    {
        $moduleName = $this->argument('module');
        $specificPanel = $this->option('panel');

        $module = Module::find($moduleName);
        if (! $module) {
            $this->error("Module '{$moduleName}' not found.");
            return;
        }

        // Get panels for this module
        $panels = FilamentModules::getModulePanels($moduleName);

        if (empty($panels)) {
            $this->warn("No panels found for module '{$moduleName}'. Make sure the module has been properly set up with Filament.");
            return;
        }

        // Filter to specific panel if requested
        if ($specificPanel) {
            $panels = array_filter($panels, fn($panel) => $panel->getId() === $specificPanel);
            if (empty($panels)) {
                $this->error("Panel '{$specificPanel}' not found in module '{$moduleName}'.");
                return;
            }
        }

        $this->generateRouteHelper($module, $panels);
    }

    /**
     * Generate the RouteHelper trait.
     */
    protected function generateRouteHelper(\Nwidart\Modules\Module $module, array $panels): void
    {
        $moduleName = $module->getStudlyName();
        $helperPath = $module->appPath('Helpers/RouteHelper.php');

        // Ensure Helpers directory exists
        $helpersDir = dirname($helperPath);
        if (! is_dir($helpersDir)) {
            mkdir($helpersDir, 0755, true);
        }

        $helperContent = $this->generateHelperContent($module, $panels);

        file_put_contents($helperPath, $helperContent);

        $this->info("✅ Generated RouteHelper trait at: {$helperPath}");
        $this->info("💡 Use the trait in your controllers/models:");
        $this->line("   use Modules\\{$moduleName}\\Helpers\\RouteHelper;");
    }

    /**
     * Generate the content for the RouteHelper trait.
     */
    protected function generateHelperContent(\Nwidart\Modules\Module $module, array $panels): string
    {
        $moduleName = $module->getStudlyName();
        $namespace = "Modules\\{$moduleName}\\Helpers";

        $content = "<?php\n\n";
        $content .= "namespace {$namespace};\n\n";
        $content .= "/**\n";
        $content .= " * Route helper trait for {$module->getName()} module.\n";
        $content .= " *\n";
        $content .= " * Generated by: php artisan module:route:helper {$module->getName()}\n";
        $content .= " */\n";
        $content .= "trait RouteHelper\n";
        $content .= "{\n";

        foreach ($panels as $panel) {
            $panelId = $panel->getId();
            $panelName = str($panelId)->after($module->getKebabName() . '-')->studly()->toString();
            $methodName = lcfirst($panelName);

            $content .= "\n";
            $content .= "    /**\n";
            $content .= "     * Get route for {$panelName} panel pages.\n";
            $content .= "     */\n";
            $content .= "    public static function {$methodName}Page(string \$page): string\n";
            $content .= "    {\n";
            $content .= "        return route(\"filament.{$panelId}.pages.{\$page}\");\n";
            $content .= "    }\n";
            $content .= "\n";
            $content .= "    /**\n";
            $content .= "     * Get route for {$panelName} panel resources.\n";
            $content .= "     */\n";
            $content .= "    public static function {$methodName}Resource(string \$resource, string \$action = 'index'): string\n";
            $content .= "    {\n";
            $content .= "        return route(\"filament.{$panelId}.resources.{\$resource}.{\$action}\");\n";
            $content .= "    }\n";
            $content .= "\n";
            $content .= "    /**\n";
            $content .= "     * Get route for {$panelName} panel resource creation.\n";
            $content .= "     */\n";
            $content .= "    public static function {$methodName}ResourceCreate(string \$resource): string\n";
            $content .= "    {\n";
            $content .= "        return route(\"filament.{$panelId}.resources.{\$resource}.create\");\n";
            $content .= "    }\n";
            $content .= "\n";
            $content .= "    /**\n";
            $content .= "     * Get route for {$panelName} panel resource editing.\n";
            $content .= "     */\n";
            $content .= "    public static function {$methodName}ResourceEdit(string \$resource, \$record): string\n";
            $content .= "    {\n";
            $content .= "        return route(\"filament.{$panelId}.resources.{\$resource}.edit\", \$record);\n";
            $content .= "    }\n";
            $content .= "\n";
            $content .= "    /**\n";
            $content .= "     * Get route for {$panelName} panel resource viewing.\n";
            $content .= "     */\n";
            $content .= "    public static function {$methodName}ResourceView(string \$resource, \$record): string\n";
            $content .= "    {\n";
            $content .= "        return route(\"filament.{$panelId}.resources.{\$resource}.view\", \$record);\n";
            $content .= "    }\n";
        }

        $content .= "}\n";

        return $content;
    }
}
